// ===== FILE: /src/features/prompts/v6PromptValidator.ts =====

/**
 * Result of the V6 Platinum Standard validation process.
 */
export interface V6ValidationResult {
  isValid: boolean;
  html: string;              // Sanitized, validated HTML
  errors: string[];          // Critical issues that block acceptance
  warnings: string[];        // Non-blocking suggestions for improvement
  autoFixesApplied: string[]; // List of corrections made during validation
  metadata: {                // For analytics and debugging
    validatedAt: string;     // ISO timestamp
    sectionsFound: string[]; // List of data-section attributes detected
    fontCompliant: boolean;  // Century Gothic enforcement status
    htmlVersion: 'HTML5' | 'unknown';
  };
}

/**
 * Configuration for the V6 validation engine.
 */
export interface V6ValidationConfig {
  requiredSections: string[];        // e.g., ['objectives', 'lesson-flow']
  requiredFont: string;              // 'Century Gothic'
  allowedHtmlTags?: string[];        // Optional whitelist (default: semantic HTML5)
  forbiddenPatterns?: RegExp[];      // e.g., markdown syntax, backticks
  maxOutputLength?: number;          // Optional character limit
}

/**
 * Sanitizes a string for safe injection into a Gemini system instruction.
 * Escapes backticks and triple-quotes while preserving legitimate HTML.
 * 
 * @param input The raw string to sanitize
 * @returns A clean string safe for prompt injection
 */
export function sanitizeForGemini(input: string): string {
  if (!input) return '';
  return input
    .replace(/`/g, '\\`')
    .replace(/"""/g, '\\"\\"\\"')
    .trim();
}

/**
 * Returns a human-readable summary of the validation result.
 * Useful for logging and activity tracking.
 * 
 * @param result The validation result object
 * @returns A formatted summary string
 */
export function getValidationSummary(result: V6ValidationResult): string {
  if (result.isValid) {
    return `✅ Valid (Sections: ${result.metadata.sectionsFound.join(', ')})`;
  }
  const errorCount = result.errors.length;
  const firstErrors = result.errors.slice(0, 2).join('; ');
  return `❌ Invalid: ${errorCount} issues (${firstErrors}${errorCount > 2 ? '...' : ''})`;
}

/**
 * Validates AI-generated HTML against V6 Platinum Standard requirements.
 * Handles markdown stripping, structural verification, and font enforcement.
 * 
 * @param html The raw HTML string generated by the AI
 * @param config Validation configuration rules
 * @returns A comprehensive validation result
 */
export function validateV6Output(html: string, config: V6ValidationConfig): V6ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const autoFixesApplied: string[] = [];
  const sectionsFound: string[] = [];
  let fontCompliant = false;
  let htmlVersion: 'HTML5' | 'unknown' = 'unknown';

  // 1. Initial Cleanup & Markdown Stripping
  let processedHtml = html
    .replace(/```html|```/gi, '') // Remove code fences
    .replace(/\*\*|__/g, '')      // Remove bold/italic markdown
    .replace(/^#{1,6}\s/gm, '')   // Remove header markdown
    .trim();

  if (html !== processedHtml) {
    autoFixesApplied.push('Stripped markdown artifacts (fences, bolding, headers)');
  }

  // 2. Length Check
  if (config.maxOutputLength && processedHtml.length > config.maxOutputLength) {
    processedHtml = processedHtml.substring(0, config.maxOutputLength) + '...';
    warnings.push(`Output truncated to ${config.maxOutputLength} characters`);
    autoFixesApplied.push('Truncated output due to length limit');
  }

  // 3. Pattern Blocking
  if (config.forbiddenPatterns) {
    config.forbiddenPatterns.forEach(pattern => {
      if (pattern.test(processedHtml)) {
        errors.push(`Forbidden pattern detected: ${pattern.toString()}`);
      }
    });
  }

  // 4. Structural Validation (DOM-based if available)
  const isBrowser = typeof window !== 'undefined' && typeof DOMParser !== 'undefined';

  if (!isBrowser) {
    warnings.push('DOMParser unavailable (SSR environment). Performing reduced regex-based validation.');
    
    // Fallback regex-based section detection
    config.requiredSections.forEach(section => {
      const regex = new RegExp(`data-section=["']${section}["']`, 'i');
      if (regex.test(processedHtml)) {
        sectionsFound.push(section);
      } else {
        errors.push(`Missing required section: ${section}`);
      }
    });

    // Fallback font check
    if (processedHtml.includes(config.requiredFont)) {
      fontCompliant = true;
    } else {
      processedHtml = `<div style="font-family: '${config.requiredFont}', sans-serif;">${processedHtml}</div>`;
      autoFixesApplied.push(`Auto-injected font-family: ${config.requiredFont} (Regex fallback)`);
      fontCompliant = true;
    }
  } else {
    // Browser-based DOM validation
    try {
      const parser = new DOMParser();
      const doc = parser.parseFromString(processedHtml, 'text/html');
      
      // Check sections
      config.requiredSections.forEach(section => {
        const element = doc.querySelector(`[data-section="${section}"]`);
        if (element) {
          sectionsFound.push(section);
        } else {
          errors.push(`Missing required section: ${section}`);
        }
      });

      // Check font compliance on root or body
      const root = doc.body.firstElementChild as HTMLElement | null;
      if (root) {
        const style = root.getAttribute('style') || '';
        if (style.includes(config.requiredFont)) {
          fontCompliant = true;
        } else {
          root.style.fontFamily = `'${config.requiredFont}', sans-serif`;
          autoFixesApplied.push(`Injected font-family: ${config.requiredFont} on root element`);
          fontCompliant = true;
        }
      } else {
        // Empty or text-only output, wrap it
        processedHtml = `<div style="font-family: '${config.requiredFont}', sans-serif;">${processedHtml}</div>`;
        autoFixesApplied.push(`Wrapped content in root div with ${config.requiredFont}`);
        fontCompliant = true;
      }

      // Check for semantic HTML5 tags
      const semanticTags = ['header', 'footer', 'main', 'section', 'article', 'nav', 'aside'];
      const hasSemantic = semanticTags.some(tag => doc.querySelector(tag) !== null);
      if (hasSemantic) {
        htmlVersion = 'HTML5';
      } else {
        warnings.push('No semantic HTML5 tags detected (header, main, section, etc.)');
      }

      processedHtml = doc.body.innerHTML;
    } catch (e) {
      errors.push(`HTML Parsing Error: ${e instanceof Error ? e.message : 'Unknown error'}`);
    }
  }

  return {
    isValid: errors.length === 0,
    html: processedHtml,
    errors,
    warnings,
    autoFixesApplied,
    metadata: {
      validatedAt: new Date().toISOString(),
      sectionsFound,
      fontCompliant,
      htmlVersion
    }
  };
}

// Test stub – enable when vitest configured:
/*
describe('validateV6Output', () => {
  it('should pass valid HTML5 with required sections', () => {
    const html = '<section data-section="objectives">Goal</section><section data-section="lesson-flow">Step 1</section>';
    const config = { requiredSections: ['objectives', 'lesson-flow'], requiredFont: 'Century Gothic' };
    const result = validateV6Output(html, config);
    expect(result.isValid).toBe(true);
  });

  it('should auto-fix missing font-family', () => {
    const html = '<div>Content</div>';
    const config = { requiredSections: [], requiredFont: 'Century Gothic' };
    const result = validateV6Output(html, config);
    expect(result.html).toContain('font-family: \'Century Gothic\'');
  });

  it('should reject markdown artifacts', () => {
    const html = '```html\n<div>Content</div>\n```';
    const config = { requiredSections: [], requiredFont: 'Century Gothic' };
    const result = validateV6Output(html, config);
    expect(result.html).not.toContain('```');
  });
});
*/
